### ISSUE TITLE
hi how does this work?

### ISSUE THREAD

**Issue by gunthejump** [00000o1/janus#68]

**Comment by crisdosaygo** [comment]
Hey @gunthejump! I might be available now. So we can start our p2p chat, please post your p2p locator in a comment below.
Don't worry, you'll get your locator in the next step.

Click this link now to go to the next step and get your p2p locator: [janus://my_p2p_locator_for/00000o1](https://00000o1.github.io/janus?data=eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDgwNjc5ODc2MzM3NDY3MTQxNDMgMiBJTiBJUDQgMTI3LjAuMC4xXHJcbnM9LVxyXG50PTAgMFxyXG5hPWdyb3VwOkJVTkRMRSAwXHJcbmE9ZXh0bWFwLWFsbG93LW1peGVkXHJcbmE9bXNpZC1zZW1hbnRpYzogV01TXHJcbm09YXBwbGljYXRpb24gMTExOTEgVURQL0RUTFMvU0NUUCB3ZWJydGMtZGF0YWNoYW5uZWxcclxuYz1JTiBJUDQgNDIuNzkuMTYxLjIyNlxyXG5hPWNhbmRpZGF0ZToyMDMzOTAxMDMwIDEgdWRwIDIxMTM5MzcxNTEgZTFlMWZlNmItZTA0NC00NWRkLTlmN2UtZGI2YzliMTgxZjZkLmxvY2FsIDYzMDEwIHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9Y2FuZGlkYXRlOjI1NjcwMzg4MzUgMSB1ZHAgMjExMzkzOTcxMSAzYTIxYjI0OC1iNmU4LTQyNjUtODFmMi1iY2M5NzMxMDkyY2IubG9jYWwgNTgwNDYgdHlwIGhvc3QgZ2VuZXJhdGlvbiAwIG5ldHdvcmstY29zdCA5OTlcclxuYT1jYW5kaWRhdGU6MzY2OTM5NjYyMyAxIHVkcCAxNjc3NzI5NTM1IDQyLjc5LjE2MS4yMjYgMTExOTEgdHlwIHNyZmx4IHJhZGRyIDAuMC4wLjAgcnBvcnQgMCBnZW5lcmF0aW9uIDAgbmV0d29yay1jb3N0IDk5OVxyXG5hPWNhbmRpZGF0ZToyMjIxNDI4NDE1IDEgdWRwIDE2Nzc3MzIwOTUgMjAwMTpiNDAwOmUyNDA6Y2MwMjoxOTEyOjRlOTE6MTE1MTpmOWM0IDU4MDQ2IHR5cCBzcmZseCByYWRkciA6OiBycG9ydCAwIGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9aWNlLXVmcmFnOkdsVGhcclxuYT1pY2UtcHdkOm1tbTRLS2JZT2hBOEFYSmU4MDRGMXJNOFxyXG5hPWZpbmdlcnByaW50OnNoYS0yNTYgRTM6QUI6NzA6NzM6RUY6M0U6MUE6NTA6MTg6ODg6QUI6NkE6OTM6RjE6QTY6MzY6NTI6RkU6OEE6RTg6REE6Qzk6NUQ6Qzc6QTY6QTc6NDM6Njk6NjE6RDc6NUE6MDVcclxuYT1zZXR1cDphY3RwYXNzXHJcbmE9bWlkOjBcclxuYT1zY3RwLXBvcnQ6NTAwMFxyXG5hPW1heC1tZXNzYWdlLXNpemU6MjYyMTQ0XHJcbiJ9&issue=https%3A%2F%2Fgithub.com%2F00000o1%2Fjanus%2Fissues%2F68%23new_comment_form)

Please paste your locator in the new comment box below.

**Comment by gunthejump** [comment]
janus://p2p_locator/eyJ0eXBlIjoiYW5zd2VyIiwic2RwIjoidj0wXHJcbm89LSA0NTAxOTMxMjA1Mzg4ODIxODU1IDIgSU4gSVA0IDEyNy4wLjAuMVxyXG5zPS1cclxudD0wIDBcclxuYT1ncm91cDpCVU5ETEUgMFxyXG5hPWV4dG1hcC1hbGxvdy1taXhlZFxyXG5hPW1zaWQtc2VtYW50aWM6IFdNU1xyXG5tPWFwcGxpY2F0aW9uIDkgVURQL0RUTFMvU0NUUCB3ZWJydGMtZGF0YWNoYW5uZWxcclxuYz1JTiBJUDQgMC4wLjAuMFxyXG5hPWNhbmRpZGF0ZToyNDQ1MDgxODQ1IDEgdWRwIDIxMTM5MzcxNTEgZTU1NzZlNDQtZGNkMy00NzRlLWIwNDEtN2I5ZTcxZjM3NDczLmxvY2FsIDU2Mjg3IHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9Y2FuZGlkYXRlOjE5MDQ3MjM1NTIgMSB1ZHAgMjExMzkzOTcxMSAwZGYzN2Q5YS0zMTFkLTRmYWYtODEyMS02MmY0OGEzNzIwZWQubG9jYWwgNTQ2NzAgdHlwIGhvc3QgZ2VuZXJhdGlvbiAwIG5ldHdvcmstY29zdCA5OTlcclxuYT1pY2UtdWZyYWc6Qi9CQ1xyXG5hPWljZS1wd2Q6eHZ2a0JUUFR3OFhadVQ5YjVVNm9VQlYrXHJcbmE9ZmluZ2VycHJpbnQ6c2hhLTI1NiBFRjpBMzo3RTo0QzpCNDpBODowMjowMjpCMzo5MTpFNTpGMjoyMzo2QjpENDo4RjpCOTpDMjoyNjo0MDpGMDpFRjpGNzpCMzowMzpGNzo5MTo2ODpBMzpEQTo0MzpEM1xyXG5hPXNldHVwOmFjdGl2ZVxyXG5hPW1pZDowXHJcbmE9c2N0cC1wb3J0OjUwMDBcclxuYT1tYXgtbWVzc2FnZS1zaXplOjI2MjE0NFxyXG4ifQ==

**Comment by crisdosaygo** [comment]
Alright you should be p2p connected now! It's safe to close this tab now and return to your p2p chat room.

**Comment by crisdosaygo** [comment]
Reopening to leave as a demo of how connection goes down. I'm switching off my local right now as I have to disconnect for flight so if you want to connect you need to fork your own copy, set up your GH token and repo URL and run `./local-webrtc-backend/run-page.html` 

Good luck! 😄

**Comment by crisdosaygo** [comment]
Image of client side connect: 

<img width="1175" alt="Screenshot 2023-11-17 at 1 12 06 PM" src="https://github.com/00000o1/janus/assets/22254235/692f6eec-0e8b-4612-bea4-e947dafc6832">

**Comment by crisdosaygo** [comment]
Please note that all the maintainer messages  (the ones from me) above the close mark, happen automatically. 

*edit: Erm, and the one below too! :) haha*

Polling and posting comments is why we required REPO_URL and GH_ACCESS_TOKEN.  (create a personal access token scoped to repo read and comments read & write for your janus repo).

**Comment by crisdosaygo** [comment]
Hey @gunthejump! I might be available now. So we can start our p2p chat, please post your p2p locator in a comment below.
Don't worry, you'll get your locator in the next step.

Click this link now to go to the next step and get your p2p locator: [janus://my_p2p_locator_for/00000o1](https://00000o1.github.io/janus?data=eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDMxNzQwMzY4MDg1NjU3NTY0MzkgMiBJTiBJUDQgMTI3LjAuMC4xXHJcbnM9LVxyXG50PTAgMFxyXG5hPWdyb3VwOkJVTkRMRSAwXHJcbmE9ZXh0bWFwLWFsbG93LW1peGVkXHJcbmE9bXNpZC1zZW1hbnRpYzogV01TXHJcbm09YXBwbGljYXRpb24gMTEwMzQgVURQL0RUTFMvU0NUUCB3ZWJydGMtZGF0YWNoYW5uZWxcclxuYz1JTiBJUDQgNDIuNzkuMTYxLjIyNlxyXG5hPWNhbmRpZGF0ZTo2NTQ1MTYxNTUgMSB1ZHAgMjExMzkzNzE1MSA5OTg2YWQyMy1hOWRhLTRlMTYtOWM4My0xYjZiNjdhMjRjMzkubG9jYWwgNTczOTEgdHlwIGhvc3QgZ2VuZXJhdGlvbiAwIG5ldHdvcmstY29zdCA5OTlcclxuYT1jYW5kaWRhdGU6MjI5NzEzNTczNCAxIHVkcCAyMTEzOTM5NzExIGNhY2M4ODczLWViOGEtNDU3Yi04NDcyLTg3M2EzYTdkMDg2Ni5sb2NhbCA2MDI0MCB0eXAgaG9zdCBnZW5lcmF0aW9uIDAgbmV0d29yay1jb3N0IDk5OVxyXG5hPWNhbmRpZGF0ZTozOTEyNTA2NDkgMSB1ZHAgMTY3NzcyOTUzNSA0Mi43OS4xNjEuMjI2IDExMDM0IHR5cCBzcmZseCByYWRkciAwLjAuMC4wIHJwb3J0IDAgZ2VuZXJhdGlvbiAwIG5ldHdvcmstY29zdCA5OTlcclxuYT1jYW5kaWRhdGU6MzkyNzcyNzY5IDEgdWRwIDE2Nzc3MzIwOTUgMjAwMTpiNDAwOmUyNDA6Y2MwMjphZDBhOmE2NjY6ZTRhNToyOTFhIDYwMjQwIHR5cCBzcmZseCByYWRkciA6OiBycG9ydCAwIGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9aWNlLXVmcmFnOnlDVXlcclxuYT1pY2UtcHdkOmZIQVJFUnlSOGZTYkRNSnZHeDNhUWFFaVxyXG5hPWZpbmdlcnByaW50OnNoYS0yNTYgNEU6MTE6Rjk6RjI6MDU6OTE6RkY6OEI6RTU6MzQ6ODE6NEI6RDA6NUI6MEM6NUY6NkQ6NUI6MDc6MUM6QjI6QkM6MTg6Qjg6QjE6NEI6MEM6NjA6N0E6MDU6MzM6QzFcclxuYT1zZXR1cDphY3RwYXNzXHJcbmE9bWlkOjBcclxuYT1zY3RwLXBvcnQ6NTAwMFxyXG5hPW1heC1tZXNzYWdlLXNpemU6MjYyMTQ0XHJcbiJ9&issue=https%3A%2F%2Fgithub.com%2F00000o1%2Fjanus%2Fissues%2F68%23new_comment_form)

Please paste your locator in the new comment box below.

**Comment by chwzr** [comment]
janus://p2p_locator/eyJ0eXBlIjoiYW5zd2VyIiwic2RwIjoidj0wXHJcbm89LSA2MDcwNTU4MTk4OTYwODE5MjM0IDIgSU4gSVA0IDEyNy4wLjAuMVxyXG5zPS1cclxudD0wIDBcclxuYT1ncm91cDpCVU5ETEUgMFxyXG5hPWV4dG1hcC1hbGxvdy1taXhlZFxyXG5hPW1zaWQtc2VtYW50aWM6IFdNU1xyXG5tPWFwcGxpY2F0aW9uIDQwMTk4IFVEUC9EVExTL1NDVFAgd2VicnRjLWRhdGFjaGFubmVsXHJcbmM9SU4gSVA0IDE0NS4yMjQuNzUuMjM0XHJcbmE9Y2FuZGlkYXRlOjE1MjQ3MjM1NDQgMSB1ZHAgMjEyMjI2MDIyMyAxOTIuMTY4LjEuMTQ3IDY0MDc3IHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWlkIDEgbmV0d29yay1jb3N0IDEwXHJcbmE9Y2FuZGlkYXRlOjI3NTY0MjY3MDAgMSB0Y3AgMTUxODI4MDQ0NyAxOTIuMTY4LjEuMTQ3IDkgdHlwIGhvc3QgdGNwdHlwZSBhY3RpdmUgZ2VuZXJhdGlvbiAwIG5ldHdvcmstaWQgMSBuZXR3b3JrLWNvc3QgMTBcclxuYT1jYW5kaWRhdGU6MjI5NzI5MzUyNyAxIHVkcCAxNjg2MDUyNjA3IDE0NS4yMjQuNzUuMjM0IDQwMTk4IHR5cCBzcmZseCByYWRkciAxOTIuMTY4LjEuMTQ3IHJwb3J0IDY0MDc3IGdlbmVyYXRpb24gMCBuZXR3b3JrLWlkIDEgbmV0d29yay1jb3N0IDEwXHJcbmE9aWNlLXVmcmFnOmY5Y2xcclxuYT1pY2UtcHdkOi9MOURuK0ovS0Fmc0Q1R0RKZGhhdlE5eFxyXG5hPWZpbmdlcnByaW50OnNoYS0yNTYgMjc6OTI6QjA6MTU6RUM6MUI6QzE6MzQ6ODQ6QUU6QTg6Njk6MTY6NTU6MTA6OTA6NUU6QkU6RTQ6ODI6OTc6NTM6MEM6Q0U6NUI6NTE6NEU6OTk6NTQ6ODY6QkU6RjNcclxuYT1zZXR1cDphY3RpdmVcclxuYT1taWQ6MFxyXG5hPXNjdHAtcG9ydDo1MDAwXHJcbmE9bWF4LW1lc3NhZ2Utc2l6ZToyNjIxNDRcclxuIn0=

**Comment by crisdosaygo** [comment]
Hey @chwzr sorry I'm not online right now! I can switch it on if you like. I'll go do that now, then you can close and reopen this issue or just open a new one! :)

**Comment by SoftwareValete** [comment]
hello

**Comment by crisdosaygo** [comment]
hi @SoftwareValete
